spring:
  datasource:
#    url: jdbc:postgresql://192.168.3.57:5432/fpodb
#    username: fpouser
#    password: fpo@123

     url: jdbc:postgresql://localhost:5432/fpo_11
     username: postgres
     password: password

